version: '3'
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: lireddit
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
     - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
