version: '3'
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: lireddit
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
     - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
volumes:
  database:
  redis:
